server:
  port: 8001

spring:
  application:
    name: cloud-provider-pyment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zzz.springcloud.payment.com.zzz.cloud.common.entity

eureka:
  instance:
    # 设置服务显示名称
    instance-id: payment01
    # 开启IP显示
    prefer-ip-address: true
    # 发送心跳间隔（秒）
    lease-renewal-interval-in-seconds: 5
    # 服务器收到最后一次心跳等待时间上限（秒）
    lease-expiration-duration-in-seconds: 10

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:7001/eureka
#      defaultZone: http://localhost:7001/eureka

